import type { DemoState, InterviewSessionRecord, QuizQuestion } from "@/lib/types";

const demoInterviewSessions: InterviewSessionRecord[] = [
  demoInterviewSession(1, "Comfortable conversation", 61, 3, 4),
  demoInterviewSession(2, "Speaking confidence", 65, 4, 5),
  demoInterviewSession(3, "Self introduction", 69, 5, 5),
  demoInterviewSession(4, "HR basics", 72, 5, 6),
];

export const careerTracks = [
  { name: "Embedded Systems", match: 94, icon: "Cpu", detail: "Firmware, microcontrollers, protocols and real hardware." },
  { name: "IoT", match: 88, icon: "Wifi", detail: "Connected devices, sensors, edge systems and cloud telemetry." },
  { name: "RF Engineering", match: 91, icon: "Radio", detail: "Radio-frequency circuits, measurements and wireless systems." },
  { name: "Radar Engineering", match: 90, icon: "Radio", detail: "Detection, ranging, Doppler and radar signal processing." },
  { name: "Antenna Engineering", match: 86, icon: "Radio", detail: "Radiation, propagation and practical antenna design." },
  { name: "Microwave Engineering", match: 84, icon: "Radio", detail: "Transmission lines, S-parameters and high-frequency circuits." },
  { name: "VLSI", match: 82, icon: "CircuitBoard", detail: "Digital design, verification, semiconductor and chip workflows." },
  { name: "Semiconductor Engineering", match: 80, icon: "CircuitBoard", detail: "Devices, fabrication, characterization and semiconductor products." },
  { name: "Signal Processing", match: 79, icon: "Activity", detail: "Signals, DSP algorithms, communications and sensing." },
  { name: "Telecommunication", match: 78, icon: "Wifi", detail: "Communication networks, transmission systems and telecom operations." },
  { name: "Wireless Communication", match: 78, icon: "Wifi", detail: "Modulation, channels, link budgets and modern radio systems." },
  { name: "Networking", match: 75, icon: "Wifi", detail: "Computer and communication networks, protocols and operations." },
  { name: "Industrial Automation", match: 76, icon: "Bot", detail: "PLC, control systems, robotics and production automation." },
  { name: "PLC", match: 74, icon: "Bot", detail: "Programmable logic controllers, ladder logic, HMI and safe control." },
  { name: "Robotics", match: 77, icon: "Bot", detail: "Sensors, control, mechanics and autonomous systems." },
  { name: "Core Electronics", match: 76, icon: "CircuitBoard", detail: "Analog, digital, power and electronic product fundamentals." },
  { name: "Software / IT", match: 73, icon: "Code2", detail: "Software engineering paths that value analytical problem solving." },
  { name: "AI + Electronics", match: 71, icon: "Sparkles", detail: "Edge AI, intelligent sensors and embedded machine learning." },
];

export const initialDemoState: DemoState = {
  profile: {
    name: "Aarav Kulkarni",
    email: "aarav.demo@example.com",
    college: "Government College of Engineering, Pune",
    branch: "Electronics & Telecommunication Engineering",
    year: "Third year",
    semester: "Semester 6",
    primaryGoal: "Placement + GATE",
    targetDate: "2027-02-15",
    weekdayHours: 2,
    saturdayHours: 3,
    sundayHours: 3,
    learningMethod: "Mixed",
    coursePreference: "Free only",
    programmingComfort: "Beginner",
    electronicsLevel: "Intermediate",
    existingSkills: ["Network Theory", "Digital Electronics", "C basics"],
    targetRoles: ["RF Engineer", "Radar Engineer"],
    targetCompanies: ["Bharat Electronics", "Qualcomm"],
    onboardingComplete: true,
  },
  prepJourneys: [],
  tasks: [
    { id: "task-signals", title: "Signals & Systems bridge", detail: "Review signal classifications and common transformations.", minutes: 25, type: "learn", status: "pending", skill: "Signals & Systems", topics: ["Signal classification", "Transformations"], priority: 5, completionCriteria: "Write a five-point explanation and two examples.", expectedOutcome: "Classify and transform common signals independently.", scheduledFor: "2026-09-15", carryForwardCount: 0 },
    { id: "task-network", title: "Network Theory practice", detail: "Solve five first-order transient questions for GATE and interviews.", minutes: 30, type: "practice", status: "pending", skill: "Network Theory", topics: ["First-order circuits", "Transients"], priority: 4, completionCriteria: "Solve five questions and review each incorrect step.", expectedOutcome: "Solve first-order circuit questions without hints.", scheduledFor: "2026-09-15", carryForwardCount: 0 },
    { id: "task-rf", title: "RF transmission lines", detail: "Understand impedance matching and the reflection coefficient.", minutes: 25, type: "learn", status: "pending", skill: "Transmission Lines", topics: ["Reflection coefficient", "Impedance matching"], priority: 4, completionCriteria: "Explain reflection coefficient and solve two examples.", expectedOutcome: "Connect impedance mismatch to reflected power.", scheduledFor: "2026-09-15", carryForwardCount: 0 },
    { id: "task-quiz", title: "Checkpoint quiz", detail: "Complete a focused 10-question fundamentals check.", minutes: 15, type: "assess", status: "pending", skill: "Signals & Systems", topics: ["Signals", "Network Theory", "RF fundamentals"], priority: 3, completionCriteria: "Score at least 70% and save weak topics.", expectedOutcome: "Know whether to advance or revise.", scheduledFor: "2026-09-15", carryForwardCount: 0 },
    { id: "task-project", title: "Radar project note", detail: "Document the signal-chain assumptions for your mini radar simulator.", minutes: 25, type: "prove", status: "pending", skill: "Radar Fundamentals", topics: ["Signal chain", "Assumptions"], priority: 4, completionCriteria: "Save one evidence note with assumptions and next tests.", expectedOutcome: "Create traceable project evidence for interview preparation.", scheduledFor: "2026-09-15", carryForwardCount: 0 },
  ],
  skills: [
    { id: "network", name: "Network Theory", group: "Foundation", state: "Assessed", progress: 68, evidence: "Quiz: 78%" },
    { id: "digital", name: "Digital Electronics", group: "Foundation", state: "Practiced", progress: 72, evidence: "4 exercises" },
    { id: "signals", name: "Signals & Systems", group: "Foundation", state: "Learning", progress: 38 },
    { id: "communication", name: "Communication Systems", group: "Core", state: "Learning", progress: 34, prerequisite: "Signals & Systems" },
    { id: "em", name: "Electromagnetic Theory", group: "Core", state: "Learning", progress: 26, prerequisite: "Engineering Mathematics" },
    { id: "antennas", name: "Antenna Fundamentals", group: "RF", state: "Not Started", progress: 8, prerequisite: "Electromagnetic Theory" },
    { id: "microwave", name: "Microwave Engineering", group: "RF", state: "Not Started", progress: 4, prerequisite: "Transmission Lines" },
    { id: "radar", name: "Radar Fundamentals", group: "RF", state: "Not Started", progress: 2, prerequisite: "Communication Systems" },
    { id: "c", name: "Embedded C", group: "Embedded", state: "Practiced", progress: 51, evidence: "2 exercises" },
  ],
  projects: [
    {
      id: "project-radar",
      name: "Low-Cost Doppler Radar Simulator",
      status: "Building",
      description: "A Python and SDR-inspired simulation for target velocity estimation and signal visualization.",
      technologies: ["Python", "DSP", "Radar"],
      components: ["Synthetic signal generator", "FFT pipeline"],
      progress: 46,
      nextMilestone: "Validate Doppler shift calculations",
      templateId: "template-radar-simulation",
      templateRevision: "1.0",
      mode: "simulation",
    },
    {
      id: "project-iot",
      name: "ESP32 Smart Irrigation System",
      status: "Planning",
      description: "Sensor-driven irrigation controller with MQTT telemetry and safe pump control.",
      technologies: ["ESP32", "C++", "MQTT"],
      components: ["ESP32", "Soil sensor", "Relay module"],
      progress: 18,
      nextMilestone: "Finalize power and wiring plan",
      mode: "hardware",
    },
  ],
  equipment: [
    { id: "equipment-laptop", name: "Laptop", model: "Windows laptop", quantity: 1, status: "working", category: "tool", notes: "Demo inventory" },
    { id: "equipment-python", name: "Python environment", model: "Python 3 + Jupyter", quantity: 1, status: "working", category: "software", notes: "Demo inventory" },
    { id: "equipment-numpy", name: "NumPy and Matplotlib", quantity: 1, status: "working", category: "software", notes: "Demo inventory" },
    { id: "equipment-uno", name: "Arduino Uno", model: "Uno R3 compatible", quantity: 1, status: "working", category: "component", notes: "Demo inventory" },
    { id: "equipment-ultrasonic", name: "Ultrasonic sensor", model: "HC-SR04", quantity: 1, status: "working", category: "component", notes: "Demo inventory" },
    { id: "equipment-servo", name: "Servo", model: "SG90", quantity: 1, status: "uncertain", category: "component", notes: "Needs a current draw check" },
    { id: "equipment-breadboard", name: "Breadboard and jumper wires", quantity: 1, status: "working", category: "tool", notes: "Demo inventory" },
  ],
  buildPreferences: {
    budget: 1200,
    currency: "INR",
    availableMinutes: 45,
    currentKnowledge: "Basic C, electronics fundamentals and beginner Python",
    targetRole: "Radar Engineer",
    difficulty: "starter",
    mode: "either",
  },
  evidenceSubmissions: [
    {
      id: "evidence-radar-test-demo",
      projectId: "project-radar",
      milestoneId: "validate-doppler",
      skillIds: ["radar", "signals"],
      type: "test_observation",
      title: "Synthetic Doppler frequency comparison",
      content: "Compared the expected Doppler shift with the FFT peak for three simulated target velocities.",
      expectedResult: "The estimated peak should move consistently with the configured target velocity.",
      actualResult: "The estimate followed the configured direction; error increased when the observation window was shortened.",
      personalContribution: "Created the test cases, plotted the spectra and documented the FFT-axis correction.",
      debuggingNotes: "The first result used an incorrect frequency axis. Rebuilt the axis using the saved sampling rate.",
      limitations: "Synthetic single-target data only; no RF hardware or live target was tested.",
      status: "AI-reviewed",
      submittedAt: "2026-09-18T10:00:00.000Z",
      reviewMethod: "ai",
      rubricVersion: "project-evidence-v1",
      feedback: "Demo AI review: the expected-versus-actual comparison is clear; add numeric error values before making performance claims.",
      reviewLimitations: "Simulated demo review. Code was not executed and no hardware result was certified.",
      simulated: true,
      fingerprint: "project-radar:test_observation:synthetic-doppler-frequency-comparison",
    },
  ],
  planAdjustments: [],
  roleExplorationAttempts: [
    {
      id: "exploration-rf-demo",
      activityId: "explore-rf-wavelength",
      track: "RF Engineering",
      completedAt: "2026-09-14T09:00:00.000Z",
      enjoyed: "yes",
      interestingPart: "Seeing how frequency changes practical antenna dimensions.",
      difficultPart: "Keeping metres and centimetres consistent.",
      wantsAnother: true,
      outputNote: "Demo attempt: calculated quarter-wave lengths for three frequencies.",
    },
  ],
  jobs: [
    { id: "job-1", company: "Bharat Electronics", role: "Graduate Apprentice — Electronics", status: "Interested", deadline: "2026-10-12", jobDescription: "Electronics graduate with communication systems, testing, documentation and embedded fundamentals." },
    { id: "job-2", company: "Qualcomm", role: "Interim Engineering Intern", status: "Applied", notes: "Revise digital communications and C.", jobDescription: "Engineering intern with C, Python, signal processing, wireless communication, debugging and clear technical documentation." },
  ],
  resumeReviews: [],
  quizScores: [62, 70, 78],
  confidenceScores: [3, 4, 5, 6],
  interviewProgram: {
    currentDay: 5,
    totalDays: 15,
    status: "active",
    completedDays: [1, 2, 3, 4],
    repeatCount: 0,
    lastAdjustmentMessage: "Your previous practice unlocked Day 5: strengths, weaknesses and goals.",
  },
  interviewSessions: demoInterviewSessions,
  weeklyMinutes: 410,
  streak: 8,
};

function demoInterviewSession(day: number, programTitle: string, averageScore: number, beforeConfidence: number, afterConfidence: number): InterviewSessionRecord {
  return {
    id: `demo-interview-${day}`,
    programDay: day,
    programTitle,
    personality: day <= 2 ? "Friendly Mentor" : "Professional HR",
    difficulty: "Beginner",
    confidenceMode: true,
    voiceEnabled: false,
    question: `Demo Day ${day} practice question`,
    answer: "This is a clearly labeled demo-session response used to preview progress tracking.",
    retryCount: 0,
    beforeConfidence,
    afterConfidence,
    evaluation: {
      scores: {
        clarity: averageScore,
        relevance: averageScore,
        technicalAccuracy: averageScore,
        answerStructure: averageScore,
        communication: averageScore,
        completeness: averageScore,
        uncertaintyHandling: averageScore,
      },
      didWell: "Completed the guided practice checkpoint.",
      improve: "Continue adding concise evidence to each answer.",
      betterStructure: "Direct answer → evidence → reflection.",
      uncertaintyFeedback: "Separate known facts from assumptions.",
    },
    evaluationSource: "local",
    averageScore,
    passed: true,
    completedAt: `2026-09-${String(10 + day).padStart(2, "0")}T10:00:00.000Z`,
  };
}

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    topic: "Network Theory",
    prompt: "For a first-order RC circuit, what primarily determines the time constant?",
    options: ["R + C", "R × C", "R ÷ C", "1 ÷ RC"],
    answer: 1,
    explanation: "The RC time constant is τ = R × C seconds.",
  },
  {
    id: "q2",
    topic: "Signals",
    prompt: "Which condition must hold for a continuous-time signal to be periodic?",
    options: ["x(t) = x(-t)", "x(t) = x(t + T) for some T > 0", "Its energy is finite", "Its mean is zero"],
    answer: 1,
    explanation: "A signal is periodic when it repeats after a positive fundamental period T.",
  },
  {
    id: "q3",
    topic: "RF Fundamentals",
    prompt: "A reflection coefficient of zero indicates:",
    options: ["Total reflection", "Perfect impedance matching", "An open circuit", "Maximum standing-wave ratio"],
    answer: 1,
    explanation: "Zero reflection coefficient means no reflected wave and therefore perfect matching.",
  },
  {
    id: "q4",
    topic: "Communication",
    prompt: "Why is modulation used in wireless communication?",
    options: ["Only to increase noise", "To translate information to a suitable carrier frequency", "To remove all bandwidth", "To eliminate antennas"],
    answer: 1,
    explanation: "Modulation shifts information onto a carrier suitable for transmission, antenna size, and spectrum allocation.",
  },
  {
    id: "q5",
    topic: "Embedded C",
    prompt: "Which keyword tells a compiler that a variable may change outside normal program flow?",
    options: ["static", "const", "volatile", "register"],
    answer: 2,
    explanation: "volatile prevents unsafe optimization of values changed by interrupts, hardware, or concurrent execution.",
  },
];

export const aptitudeQuestions: QuizQuestion[] = [
  { id: "a1", topic: "Quantitative Aptitude", prompt: "A task takes 12 days for 8 people at the same rate. How many days would 6 people need?", options: ["9", "12", "16", "18"], answer: 2, explanation: "Total work is 8 × 12 = 96 person-days; 96 ÷ 6 = 16 days." },
  { id: "a2", topic: "Logical Reasoning", prompt: "All sensors are devices. Some devices are wireless. Which conclusion must be true?", options: ["All sensors are wireless", "Some sensors are wireless", "No sensor is wireless", "Sensors are devices"], answer: 3, explanation: "Only the original universal statement must be true: every sensor is a device." },
  { id: "a3", topic: "Verbal Ability", prompt: "Choose the clearest professional sentence.", options: ["I done the testing yesterday.", "Testing was completed yesterday, and I documented the results.", "Yesterday testing complete by me.", "The test, it was done."], answer: 1, explanation: "The sentence is grammatically correct, direct and includes a useful result." },
  { id: "a4", topic: "Data Interpretation", prompt: "Quiz accuracy rises from 60% to 75%. What is the increase in percentage points?", options: ["15", "20", "25", "35"], answer: 0, explanation: "Percentage-point change is 75 − 60 = 15 points." },
  { id: "a5", topic: "Quantitative Aptitude", prompt: "A ₹2,000 component kit receives a 10% discount. What is the final price?", options: ["₹1,600", "₹1,800", "₹1,900", "₹2,200"], answer: 1, explanation: "Ten percent of ₹2,000 is ₹200, so the discounted price is ₹1,800." },
];

export const verifiedResources = [
  { title: "Signals and Systems", provider: "NPTEL · IIT Bombay", level: "Foundation", duration: "Self-paced archive", cost: "Free to learn", topics: "LTI systems, Fourier and Laplace transforms", why: "Builds the prerequisite base for RF, radar and communications.", url: "https://nptel.ac.in/courses/117101055", verified: "Verified 15 Sep 2026" },
  { title: "ESP-IDF Programming Guide", provider: "Espressif", level: "Beginner–Advanced", duration: "Self-paced", cost: "Free", topics: "ESP32, drivers, networking and system APIs", why: "Primary-source documentation for credible embedded projects.", url: "https://docs.espressif.com/projects/esp-idf/en/stable/esp32/", verified: "Verified 15 Sep 2026" },
  { title: "Introduction to Internet of Things", provider: "NPTEL", level: "Beginner", duration: "12 weeks", cost: "Free to learn", topics: "IoT architecture, sensors, protocols and cloud", why: "A structured foundation before building connected hardware.", url: "https://nptel.ac.in/courses/106105166", verified: "Verified 15 Sep 2026" },
];
